# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'this.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from .src import *
from .backgroundDesign import accountFormBg


class Account(object):
    def __init__(self, MainWindow):
        self.login = QtWidgets.QFrame(MainWindow)
        self.login.setGeometry(QtCore.QRect(160, 140, 431, 441))
        self.login.setStyleSheet("border-radius: 25px;\n")
        self.login.setGraphicsEffect(shadow(89))
        self.login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(self.login)
        self.label.setGeometry(QtCore.QRect(140, 40, 144, 29))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label1 = QtWidgets.QLabel(self.login)
        self.label1.setGeometry(QtCore.QRect(140, 95, 144, 29))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
    
        self.comboBox = QtWidgets.QComboBox(self.login)
        self.comboBox.setGeometry(QtCore.QRect(140, 150, 154, 32))
        self.comboBox.setGraphicsEffect(shadow(110))
        self.comboBox.setPlaceholderText('Account Type')
        self.comboBox.setStyleSheet("QComboBox {\n"
        "border: 1px solid;\n"
        "border-color:#FFFFFF;\n"
        "border-radius: 10px;\n"
        "padding-left: 10px;\n"
        "}\n"
        "QComboBox QAbstractItemView {\n"
        "selection-background-color:#DADADA;\n"
        "selection-color: #000000;\n"
        "}\n"
        "QComboBox::drop-down{\n"
        "border:0px;\n"
        "}\n"
        "QComboBox::down-arrow{\n"
        "image:url(:/Icon/down-arrow.png);\n"
        "height: 15px;\n"
        "width: 15px;\n"
        "padding-left:-15px;\n"
        "}\n"
        "QComboBox:hover{\n"
        "border-color:#5992EC;\n"
        "color:#5992EC;\n"
        "}"
        "QScrollBar{\n"
            "background: #e1e1e1;\n"
            "width: 8px;\n"
        "}"
        "QScrollBar::handle:vertical {"
            "background: #999999;\n"
            "border-radius: 1px;\n"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "background: #686868;\n"
        "}")

        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/google.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/instagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/snapchat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/apple-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/microsoft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/linkedin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/reddit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Social media icons/Social Media icon/graduate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon10, "")
        icon12.addPixmap(QtGui.QPixmap(":/Social media icons/ellipsis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, "")
        self.comboBox.currentIndexChanged.connect(self.type_entry)

        self.lineEdit = QtWidgets.QLineEdit(self.login)
        self.lineEdit.setGeometry(QtCore.QRect(140, 210, 154, 32))
        self.lineEdit.setText( self.comboBox.currentText())
        self.lineEdit.setDisabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)        
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#FFFFFF}"
        "QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit.setGraphicsEffect(shadow(110))
        self.lineEdit.setObjectName("lineEdit")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 270, 154, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#FFFFFF}"
        "QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setGraphicsEffect(shadow(110))

        self.lineEdit_2 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 330, 154, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#FFFFFF}"
        "QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setGraphicsEffect(shadow(110))
        self.pushButton1 = QtWidgets.QPushButton(self.login)
        self.pushButton1.setGeometry(QtCore.QRect(335, 340, 20, 16))
        self.pushButton1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon)
        self.pushButton1.setObjectName("pushButton")
        self.pushButton1.setStyleSheet("background-color: #FBFBFB;\n"
    	"border-radius:15px;")
        self.pushButton1.pressed.connect(lambda:show(self.pushButton1, self.lineEdit_2))
        self.pushButton1.released.connect(lambda:hide(self.pushButton1, self.lineEdit_2))
        self.generate = QtWidgets.QPushButton(self.login)
        self.generate.setGeometry(QtCore.QRect(365, 340, 20, 16))
        self.generate
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate.setIcon(icon)
        self.generate.setObjectName("generate")
        
        self.pushButton = QtWidgets.QPushButton(self.login)
        self.pushButton.setGeometry(QtCore.QRect(136, 390, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
        "background-color: #FEFEFE;\n"
        "border-radius: 15px;\n"
        "padding-right: 55px;\n"
        "}"
        "QPushButton:hover{\n"
        "background-color: #E3DFDF;\n"
        "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setGraphicsEffect(shadow(110))
        self.pushButton.setObjectName("pushButton")
        
        accountFormBg(self.login)
        self.pushButton2 = QtWidgets.QPushButton(self.login)
        self.pushButton2.setGeometry(QtCore.QRect(380, 390, 31, 31))
        self.pushButton2.setStyleSheet("background-color: #365797;\n"
        "border-radius: 15px;\n")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icon/log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon11)
        self.pushButton2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.setGraphicsEffect(shadow(210))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Record Section"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Account Name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.pushButton.setText(_translate("MainWindow", "       Store"))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.comboBox.setItemText(0, _translate("MainWindow", "Google"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Facebook"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Instagram"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Snapchat"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Twitter"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Spotify"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Apple"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Microsoft"))
        self.comboBox.setItemText(8, _translate("MainWindow", "GitHub"))
        self.comboBox.setItemText(9, _translate("MainWindow", "LinkedIn"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Reddit"))
        self.comboBox.setItemText(11, _translate("MainWindow", "University"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Others"))

    def type_entry(self):
        if self.comboBox.currentText() == 'Others':
            self.lineEdit.clear()
            self.lineEdit.setEnabled(True)
        else:
            self.lineEdit.setText(self.comboBox.currentText())
            self.lineEdit.setDisabled(True)

    def hide(self): self.login.hide()
    def master(self): return self.login
    def toBeFormatted(self): return self.label1
    def accountNameEntry(self): return self.lineEdit
    def passwordEntry(self): return self.lineEdit_2
    def userNameEntry(self): return self.lineEdit_3
    def accountType(self): return self.comboBox
    def storeButton(self): return self.pushButton
    def showHideButton(self): return self.pushButton1
    def generateButton(self): return self.generate
    def logoutButton(self): return self.pushButton2
