# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'this.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from .backgroundDesign import authorizeFromBg
from .src import *

class Authorize(object):

    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../google.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #000000")
        MainWindow.setIconSize(QtCore.QSize(5, 5))
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(160, 140, 431, 441))
        self.frame.setStyleSheet("background-color: #ffffff;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setGraphicsEffect(shadow(90))
        
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(136, 90, 133, 29))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.format_lable = QtWidgets.QLabel(self.frame)
        self.format_lable.setGeometry(QtCore.QRect(140, 150, 146, 29))
        self.format_lable.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.format_lable.setFont(font)
        self.format_lable.setObjectName("format_lable")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setGeometry(QtCore.QRect(120, 220, 220, 30))
        self.lineEdit.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#EBEBEB}\n"
" QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setGraphicsEffect(shadow(110))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)        
        self.lineEdit.setFont(font)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 230, 24, 13))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setStyleSheet("QPushButton{\n"
"        background-color: #FFFFFF;\n"
"        border-radius: 5px;\n"
"        }\n"
"        QPushButton:hover{\n"
"        background-color: #E3DFDF;\n"
"        }")
        self.pushButton.pressed.connect(lambda: show(self.pushButton, self.lineEdit))
        self.pushButton.released.connect(lambda: hide(self.pushButton, self.lineEdit))
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 280, 220, 30))
        self.pushButton_2.setGraphicsEffect(shadow(110))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"        background-color: #FFFFFF;\n"
"        border-radius: 15px;\n"
"        padding-right: 80px;\n"
"        }\n"
"        QPushButton:hover{\n"
"        background-color: #E3DFDF;\n"
"        }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/submit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")

        authorizeFromBg(self.frame)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.frame.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UrePass"))
        self.label.setText(_translate("MainWindow", "Authorization"))
        self.format_lable.setText(_translate("MainWindow", "To be fromated"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.pushButton_2.setText(_translate("MainWindow", "              Submit"))

    def master(self): return self.frame    

    def toBeFormattedLable(self): return self.format_lable

    def passwordEntry(self): return self.lineEdit

    def showHideButton(self): return self.pushButton

    def submitButton(self): return self.pushButton_2