from .src import *

def mainWindowBg(MainWindow):    
    _2 = QtWidgets.QFrame(MainWindow)
    _2.setGeometry(QtCore.QRect(20, 520, 30, 30))
    _2.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _2.setFrameShadow(QtWidgets.QFrame.Raised)
    _18 = QtWidgets.QFrame(_2)
    _18.setGeometry(QtCore.QRect(16, 17, 18, 17))
    _18.setStyleSheet("background-color: #ffffff")
    _18.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _18.setFrameShadow(QtWidgets.QFrame.Raised)
    _3 = QtWidgets.QFrame(MainWindow)
    _3.setGeometry(QtCore.QRect(590, 530, 110, 110))
    _3.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 55px;")
    _3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _3.setFrameShadow(QtWidgets.QFrame.Raised)
    _8 = QtWidgets.QFrame(_3)
    _8.setGeometry(QtCore.QRect(48, 47, 10, 10))
    _8.setStyleSheet("background-color: #ffffff;\n"
    "border-radius:5px;")
    _8.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _8.setFrameShadow(QtWidgets.QFrame.Raised)
    _19 = QtWidgets.QFrame(_8)
    _19.setGeometry(QtCore.QRect(0, 0, 10, 10))
    _19.setStyleSheet("background-color: #ffffff;\n"
    "border-radius:5px;")
    _19.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _19.setFrameShadow(QtWidgets.QFrame.Raised)
    _4 = QtWidgets.QFrame(MainWindow)
    _4.setGeometry(QtCore.QRect(-30, -30, 110, 110))
    _4.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 55px;")
    _4.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _4.setFrameShadow(QtWidgets.QFrame.Raised)
    _20 = QtWidgets.QFrame(_4)
    _20.setGeometry(QtCore.QRect(56, 55, 10, 10))
    _20.setStyleSheet("background-color: #ffffff;\n"
    "border-radius:5px;")
    _20.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _20.setFrameShadow(QtWidgets.QFrame.Raised)
    _5 = QtWidgets.QFrame(MainWindow)
    _5.setGeometry(QtCore.QRect(620, 40, 31, 29))
    _5.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _5.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _5.setFrameShadow(QtWidgets.QFrame.Raised)
    _13 = QtWidgets.QFrame(_5)
    _13.setGeometry(QtCore.QRect(22, 10, 10, 10))
    _13.setStyleSheet("background-color: #ffffff")
    _13.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _13.setFrameShadow(QtWidgets.QFrame.Raised)
    _6 = QtWidgets.QFrame(MainWindow)
    _6.setGeometry(QtCore.QRect(390, 600, 30, 29))
    _6.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _6.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _6.setFrameShadow(QtWidgets.QFrame.Raised)
    _22 = QtWidgets.QFrame(_6)
    _22.setGeometry(QtCore.QRect(9, -2, 12, 10))
    _22.setStyleSheet("background-color: #ffffff")
    _22.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _22.setFrameShadow(QtWidgets.QFrame.Raised)
    _7 = QtWidgets.QFrame(MainWindow)
    _7.setGeometry(QtCore.QRect(610, 270, 30, 30))
    _7.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _7.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _7.setFrameShadow(QtWidgets.QFrame.Raised)
    _14 = QtWidgets.QFrame(_7)
    _14.setGeometry(QtCore.QRect(17, 17, 20, 20))
    _14.setStyleSheet("background-color: #ffffff")
    _14.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _14.setFrameShadow(QtWidgets.QFrame.Raised)
    _9 = QtWidgets.QFrame(MainWindow)
    _9.setGeometry(QtCore.QRect(580, 450, 30, 29))
    _9.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _9.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _9.setFrameShadow(QtWidgets.QFrame.Raised)
    _15 = QtWidgets.QFrame(_9)
    _15.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _15.setStyleSheet("background-color: #ffffff")
    _15.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _15.setFrameShadow(QtWidgets.QFrame.Raised)
    _10 = QtWidgets.QFrame(MainWindow)
    _10.setGeometry(QtCore.QRect(90, 120, 30, 31))
    _10.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _10.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _10.setFrameShadow(QtWidgets.QFrame.Raised)
    frame = QtWidgets.QFrame(_10)
    frame.setGeometry(QtCore.QRect(20, 20, 14, 12))
    frame.setStyleSheet("background-color: #ffffff")
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    _11 = QtWidgets.QFrame(MainWindow)
    _11.setGeometry(QtCore.QRect(530, 150, 30, 30))
    _11.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _11.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _11.setFrameShadow(QtWidgets.QFrame.Raised)
    _21 = QtWidgets.QFrame(_11)
    _21.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _21.setStyleSheet("background-color: #ffffff")
    _21.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _21.setFrameShadow(QtWidgets.QFrame.Raised)
    _16 = QtWidgets.QFrame(MainWindow)
    _16.setGeometry(QtCore.QRect(0, 590, 30, 29))
    _16.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _16.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _16.setFrameShadow(QtWidgets.QFrame.Raised)
    _17 = QtWidgets.QFrame(_16)
    _17.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _17.setStyleSheet("background-color: #ffffff")
    _17.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _17.setFrameShadow(QtWidgets.QFrame.Raised)
    _12 = QtWidgets.QFrame(MainWindow)
    _12.setGeometry(QtCore.QRect(100, 290, 30, 31))
    _12.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _12.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _12.setFrameShadow(QtWidgets.QFrame.Raised)
    _23 = QtWidgets.QFrame(_12)
    _23.setGeometry(QtCore.QRect(20, 20, 14, 12))
    _23.setStyleSheet("background-color: #ffffff")
    _23.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _23.setFrameShadow(QtWidgets.QFrame.Raised)
    _24 = QtWidgets.QFrame(MainWindow)
    _24.setGeometry(QtCore.QRect(140, 440, 30, 29))
    _24.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _24.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _24.setFrameShadow(QtWidgets.QFrame.Raised)
    _25 = QtWidgets.QFrame(_24)
    _25.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _25.setStyleSheet("background-color: #ffffff")
    _25.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _25.setFrameShadow(QtWidgets.QFrame.Raised)
    _26 = QtWidgets.QFrame(MainWindow)
    _26.setGeometry(QtCore.QRect(180, 540, 30, 31))
    _26.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _26.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _26.setFrameShadow(QtWidgets.QFrame.Raised)
    _27 = QtWidgets.QFrame(_26)
    _27.setGeometry(QtCore.QRect(20, 20, 14, 12))
    _27.setStyleSheet("background-color: #ffffff")
    _27.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _27.setFrameShadow(QtWidgets.QFrame.Raised)
    _28 = QtWidgets.QFrame(MainWindow)
    _28.setGeometry(QtCore.QRect(90, -17, 584, 20))
    _28.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _28.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _28.setFrameShadow(QtWidgets.QFrame.Raised)
    _29 = QtWidgets.QFrame(MainWindow)
    _29.setGeometry(QtCore.QRect(674, 0, 590, 530))
    _29.setStyleSheet("background-color: #5992EC;")
    _29.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _29.setFrameShadow(QtWidgets.QFrame.Raised)
    _30 = QtWidgets.QFrame(MainWindow)
    _30.setGeometry(QtCore.QRect(0, 610, 584, 30))
    _30.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _30.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _30.setFrameShadow(QtWidgets.QFrame.Raised)
    _31 = QtWidgets.QFrame(MainWindow)
    _31.setGeometry(QtCore.QRect(-587, 90, 590, 510))
    _31.setStyleSheet("background-color: #5992EC;")
    _31.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _31.setFrameShadow(QtWidgets.QFrame.Raised)
    _32 = QtWidgets.QFrame(MainWindow)
    _32.setGeometry(QtCore.QRect(650, -80, 110, 110))
    _32.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 55px;")
    _32.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _32.setFrameShadow(QtWidgets.QFrame.Raised)
    _33 = QtWidgets.QFrame(_32)
    _33.setGeometry(QtCore.QRect(48, 47, 10, 10))
    _33.setStyleSheet("background-color: #ffffff;\n"
    "border-radius:5px;")
    _33.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _33.setFrameShadow(QtWidgets.QFrame.Raised)
    _34 = QtWidgets.QFrame(_33)
    _34.setGeometry(QtCore.QRect(0, 0, 10, 10))
    _34.setStyleSheet("background-color: #ffffff;\n"
    "border-radius:5px;")
    _34.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _34.setFrameShadow(QtWidgets.QFrame.Raised)
    _35 = QtWidgets.QFrame(MainWindow)
    _35.setGeometry(QtCore.QRect(10, 190, 30, 29))
    _35.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _35.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _35.setFrameShadow(QtWidgets.QFrame.Raised)
    _36 = QtWidgets.QFrame(_35)
    _36.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _36.setStyleSheet("background-color: #ffffff")
    _36.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _36.setFrameShadow(QtWidgets.QFrame.Raised)
    _37 = QtWidgets.QFrame(MainWindow)
    _37.setGeometry(QtCore.QRect(-20, 300, 30, 29))
    _37.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _37.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _37.setFrameShadow(QtWidgets.QFrame.Raised)
    _38 = QtWidgets.QFrame(_37)
    _38.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _38.setStyleSheet("background-color: #ffffff")
    _38.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _38.setFrameShadow(QtWidgets.QFrame.Raised)
    _39 = QtWidgets.QFrame(MainWindow)
    _39.setGeometry(QtCore.QRect(-10, 390, 30, 31))
    _39.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _39.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _39.setFrameShadow(QtWidgets.QFrame.Raised)
    _41 = QtWidgets.QFrame(_39)
    _41.setGeometry(QtCore.QRect(20, 20, 14, 12))
    _41.setStyleSheet("background-color: #ffffff")
    _41.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _41.setFrameShadow(QtWidgets.QFrame.Raised)
    _40 = QtWidgets.QFrame(MainWindow)
    _40.setGeometry(QtCore.QRect(350, 330, 30, 29))
    _40.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _40.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _40.setFrameShadow(QtWidgets.QFrame.Raised)
    _42 = QtWidgets.QFrame(_40)
    _42.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _42.setStyleSheet("background-color: #ffffff")
    _42.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _42.setFrameShadow(QtWidgets.QFrame.Raised)
    _43 = QtWidgets.QFrame(_40)
    _43.setGeometry(QtCore.QRect(0, 0, 30, 29))
    _43.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _43.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _43.setFrameShadow(QtWidgets.QFrame.Raised)
    _44 = QtWidgets.QFrame(_43)
    _44.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _44.setStyleSheet("background-color: #ffffff")
    _44.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _44.setFrameShadow(QtWidgets.QFrame.Raised)
    _45 = QtWidgets.QFrame(MainWindow)
    _45.setGeometry(QtCore.QRect(390, 170, 30, 29))
    _45.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _45.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _45.setFrameShadow(QtWidgets.QFrame.Raised)
    _46 = QtWidgets.QFrame(_45)
    _46.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _46.setStyleSheet("background-color: #ffffff")
    _46.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _46.setFrameShadow(QtWidgets.QFrame.Raised)
    _47 = QtWidgets.QFrame(MainWindow)
    _47.setGeometry(QtCore.QRect(250, 100, 30, 29))
    _47.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _47.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _47.setFrameShadow(QtWidgets.QFrame.Raised)
    _48 = QtWidgets.QFrame(_47)
    _48.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _48.setStyleSheet("background-color: #ffffff")
    _48.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _48.setFrameShadow(QtWidgets.QFrame.Raised)
    _49 = QtWidgets.QFrame(MainWindow)
    _49.setGeometry(QtCore.QRect(480, 90, 30, 30))
    _49.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _49.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _49.setFrameShadow(QtWidgets.QFrame.Raised)
    _52 = QtWidgets.QFrame(_49)
    _52.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _52.setStyleSheet("background-color: #ffffff")
    _52.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _52.setFrameShadow(QtWidgets.QFrame.Raised)
    _54 = QtWidgets.QFrame(MainWindow)
    _54.setGeometry(QtCore.QRect(510, 490, 30, 30))
    _54.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _54.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _54.setFrameShadow(QtWidgets.QFrame.Raised)
    _55 = QtWidgets.QFrame(_54)
    _55.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _55.setStyleSheet("background-color: #ffffff")
    _55.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _55.setFrameShadow(QtWidgets.QFrame.Raised)
    _56 = QtWidgets.QFrame(MainWindow)
    _56.setGeometry(QtCore.QRect(390, 470, 30, 30))
    _56.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _56.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _56.setFrameShadow(QtWidgets.QFrame.Raised)
    _57 = QtWidgets.QFrame(_56)
    _57.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _57.setStyleSheet("background-color: #ffffff")
    _57.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _57.setFrameShadow(QtWidgets.QFrame.Raised)
    _58 = QtWidgets.QFrame(MainWindow)
    _58.setGeometry(QtCore.QRect(310, 590, 30, 30))
    _58.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _58.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _58.setFrameShadow(QtWidgets.QFrame.Raised)
    _59 = QtWidgets.QFrame(_58)
    _59.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _59.setStyleSheet("background-color: #ffffff")
    _59.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _59.setFrameShadow(QtWidgets.QFrame.Raised)
    _60 = QtWidgets.QFrame(MainWindow)
    _60.setGeometry(QtCore.QRect(100, 590, 30, 30))
    _60.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _60.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _60.setFrameShadow(QtWidgets.QFrame.Raised)
    _61 = QtWidgets.QFrame(_60)
    _61.setGeometry(QtCore.QRect(-6, 17, 20, 20))
    _61.setStyleSheet("background-color: #ffffff")
    _61.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _61.setFrameShadow(QtWidgets.QFrame.Raised)
    _62 = QtWidgets.QFrame(MainWindow)
    _62.setGeometry(QtCore.QRect(260, 270, 30, 29))
    _62.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _62.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _62.setFrameShadow(QtWidgets.QFrame.Raised)
    _63 = QtWidgets.QFrame(_62)
    _63.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _63.setStyleSheet("background-color: #ffffff")
    _63.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _63.setFrameShadow(QtWidgets.QFrame.Raised)
    _64 = QtWidgets.QFrame(_62)
    _64.setGeometry(QtCore.QRect(0, 0, 30, 29))
    _64.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _64.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _64.setFrameShadow(QtWidgets.QFrame.Raised)
    _65 = QtWidgets.QFrame(_64)
    _65.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _65.setStyleSheet("background-color: #ffffff")
    _65.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _65.setFrameShadow(QtWidgets.QFrame.Raised)
    _66 = QtWidgets.QFrame(MainWindow)
    _66.setGeometry(QtCore.QRect(120, 40, 30, 29))
    _66.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _66.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _66.setFrameShadow(QtWidgets.QFrame.Raised)
    _67 = QtWidgets.QFrame(_66)
    _67.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _67.setStyleSheet("background-color: #ffffff")
    _67.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _67.setFrameShadow(QtWidgets.QFrame.Raised)
    _68 = QtWidgets.QFrame(MainWindow)
    _68.setGeometry(QtCore.QRect(560, 370, 30, 29))
    _68.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _68.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _68.setFrameShadow(QtWidgets.QFrame.Raised)
    _69 = QtWidgets.QFrame(_68)
    _69.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _69.setStyleSheet("background-color: #ffffff")
    _69.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _69.setFrameShadow(QtWidgets.QFrame.Raised)
    _70 = QtWidgets.QFrame(MainWindow)
    _70.setGeometry(QtCore.QRect(490, 290, 30, 29))
    _70.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _70.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _70.setFrameShadow(QtWidgets.QFrame.Raised)
    _71 = QtWidgets.QFrame(_70)
    _71.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _71.setStyleSheet("background-color: #ffffff")
    _71.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _71.setFrameShadow(QtWidgets.QFrame.Raised)
    _72 = QtWidgets.QFrame(MainWindow)
    _72.setGeometry(QtCore.QRect(540, 600, 30, 29))
    _72.setStyleSheet("background-color: #5992EC;\n"
    "border-radius: 15px;")
    _72.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _72.setFrameShadow(QtWidgets.QFrame.Raised)
    _73 = QtWidgets.QFrame(_72)
    _73.setGeometry(QtCore.QRect(20, 10, 19, 10))
    _73.setStyleSheet("background-color: #ffffff")
    _73.setFrameShape(QtWidgets.QFrame.StyledPanel)
    _73.setFrameShadow(QtWidgets.QFrame.Raised)

def registerFormBg(Master):
    cube1 = QtWidgets.QFrame(Master)
    cube1.setGeometry(QtCore.QRect(-120, -140, 211, 221))
    cube1.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 55px;")
    cube1.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube1.setFrameShadow(QtWidgets.QFrame.Raised)
    cube1.setObjectName("cube1")

    cube2 = QtWidgets.QFrame(Master)
    cube2.setGeometry(QtCore.QRect(340, 360, 211, 221))
    cube2.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 55px;")
    cube2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube2.setFrameShadow(QtWidgets.QFrame.Raised)
    cube2.setObjectName("cube2")
    
    frame = QtWidgets.QFrame(Master)
    frame.setGeometry(QtCore.QRect(101, -50, 320, 54))
    frame.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 0px")
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    frame.setObjectName("frame")
    
    frame_2 = QtWidgets.QFrame(Master)
    frame_2.setGeometry(QtCore.QRect(-10, 437, 340, 6))
    frame_2.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 0px")
    frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_2.setObjectName("frame_2")
    
    frame_3 = QtWidgets.QFrame(Master)
    frame_3.setGeometry(QtCore.QRect(427, -20, 370, 370))
    frame_3.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 0px")
    frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_3.setObjectName("frame_3")
    
    frame_5 = QtWidgets.QFrame(Master)
    frame_5.setGeometry(QtCore.QRect(-316, 91, 320, 350))
    frame_5.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 0px")
    frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_5.setObjectName("frame_5")
    cube2_2 = QtWidgets.QFrame(Master)
    cube2_2.setGeometry(QtCore.QRect(410, -190, 211, 221))
    cube2_2.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 55px;")
    cube2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube2_2.setFrameShadow(QtWidgets.QFrame.Raised)
    cube2_2.setObjectName("cube2_2")
    
    cube2_3 = QtWidgets.QFrame(Master)
    cube2_3.setGeometry(QtCore.QRect(-180, 420, 211, 221))
    cube2_3.setStyleSheet("background-color:#4169B6;\n"
"border-radius: 55px;")
    cube2_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube2_3.setFrameShadow(QtWidgets.QFrame.Raised)
    cube2_3.setObjectName("cube2_3")
    

def accountFormBg(Master):
    cube_login = QtWidgets.QFrame(Master)
    cube_login.setGeometry(QtCore.QRect(-60, -50, 140, 130))
    cube_login.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px;")
    cube_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login.setObjectName("cube_login")
    cube_login_7 = QtWidgets.QFrame(cube_login)
    cube_login_7.setGeometry(QtCore.QRect(0, 0, 140, 130))
    cube_login_7.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px;")
    cube_login_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_7.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_7.setObjectName("cube_login_7")
    cube_login_2 = QtWidgets.QFrame(Master)
    cube_login_2.setGeometry(QtCore.QRect(90, -46, 340, 50))
    cube_login_2.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 0px;")
    cube_login_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_2.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_2.setObjectName("cube_login_2")
    cube_login_3 = QtWidgets.QFrame(Master)
    cube_login_3.setGeometry(QtCore.QRect(427, -100, 350, 450))
    cube_login_3.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 0px;")
    cube_login_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_3.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_3.setObjectName("cube_login_3")
    cube_login_4 = QtWidgets.QFrame(Master)
    cube_login_4.setGeometry(QtCore.QRect(-110, 437, 450, 450))
    cube_login_4.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 0px;")
    cube_login_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_4.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_4.setObjectName("cube_login_4")
    cube_login_5 = QtWidgets.QFrame(Master)
    cube_login_5.setGeometry(QtCore.QRect(350, 360, 140, 130))
    cube_login_5.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px;")
    cube_login_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_5.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_5.setObjectName("cube_login_5")
    cube_login_6 = QtWidgets.QFrame(Master)
    cube_login_6.setGeometry(QtCore.QRect(-446, 90, 450, 450))
    cube_login_6.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 0px;")
    cube_login_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_6.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_6.setObjectName("cube_login_6")
    cube_login_8 = QtWidgets.QFrame(Master)
    cube_login_8.setGeometry(QtCore.QRect(400, -100, 140, 130))
    cube_login_8.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px;")
    cube_login_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_8.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_8.setObjectName("cube_login_8")
    cube_login_9 = QtWidgets.QFrame(Master)
    cube_login_9.setGeometry(QtCore.QRect(-110, 410, 140, 130))
    cube_login_9.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px;")
    cube_login_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_9.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_9.setObjectName("cube_login_9")

def loginFormBg(Master):
    cube_login = QtWidgets.QFrame(Master)
    cube_login.setGeometry(QtCore.QRect(-60, -50, 140, 130))
    cube_login.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login.setObjectName("cube_login")
    cube_login_2 = QtWidgets.QFrame(Master)
    cube_login_2.setGeometry(QtCore.QRect(90, -46, 340, 50))
    cube_login_2.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_2.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_2.setObjectName("cube_login_2")
    cube_login_3 = QtWidgets.QFrame(Master)
    cube_login_3.setGeometry(QtCore.QRect(427, -100, 350, 450))
    cube_login_3.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_3.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_3.setObjectName("cube_login_3")
    cube_login_4 = QtWidgets.QFrame(Master)
    cube_login_4.setGeometry(QtCore.QRect(-110, 437, 450, 450))
    cube_login_4.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_4.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_4.setObjectName("cube_login_4")
    cube_login_5 = QtWidgets.QFrame(Master)
    cube_login_5.setGeometry(QtCore.QRect(350, 360, 140, 130))
    cube_login_5.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_5.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_5.setObjectName("cube_login_5")
    cube_login_6 = QtWidgets.QFrame(Master)
    cube_login_6.setGeometry(QtCore.QRect(-446, 90, 450, 450))
    cube_login_6.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_6.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_6.setObjectName("cube_login_6")

def viewBg(Master):
    cube_login = QtWidgets.QFrame(Master)
    cube_login.setGeometry(QtCore.QRect(-60, -50, 140, 130))
    cube_login.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login.setObjectName("cube_login")
    cube_login_7 = QtWidgets.QFrame(cube_login)
    cube_login_7.setGeometry(QtCore.QRect(0, 0, 140, 130))
    cube_login_7.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_7.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_7.setObjectName("cube_login_7")
    cube_login_2 = QtWidgets.QFrame(Master)
    cube_login_2.setGeometry(QtCore.QRect(90, -46, 340, 50))
    cube_login_2.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_2.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_2.setObjectName("cube_login_2")
    cube_login_3 = QtWidgets.QFrame(Master)
    cube_login_3.setGeometry(QtCore.QRect(427, -100, 350, 450))
    cube_login_3.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_3.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_3.setObjectName("cube_login_3")
    cube_login_4 = QtWidgets.QFrame(Master)
    cube_login_4.setGeometry(QtCore.QRect(-110, 437, 450, 450))
    cube_login_4.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_4.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_4.setObjectName("cube_login_4")
    cube_login_5 = QtWidgets.QFrame(Master)
    cube_login_5.setGeometry(QtCore.QRect(350, 360, 140, 130))
    cube_login_5.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_5.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_5.setObjectName("cube_login_5")
    cube_login_6 = QtWidgets.QFrame(Master)
    cube_login_6.setGeometry(QtCore.QRect(-446, 90, 450, 450))
    cube_login_6.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 0px;")
    cube_login_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_6.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_6.setObjectName("cube_login_6")
    cube_login_8 = QtWidgets.QFrame(Master)
    cube_login_8.setGeometry(QtCore.QRect(400, -100, 140, 130))
    cube_login_8.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_8.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_8.setObjectName("cube_login_8")
    cube_login_9 = QtWidgets.QFrame(Master)
    cube_login_9.setGeometry(QtCore.QRect(-110, 410, 140, 130))
    cube_login_9.setStyleSheet("background-color: #4169B6;\n"
    "border-radius: 55px;")
    cube_login_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
    cube_login_9.setFrameShadow(QtWidgets.QFrame.Raised)
    cube_login_9.setObjectName("cube_login_9")


def authorizeFromBg(Master):
        frame_16 = QtWidgets.QFrame(Master)
        frame_16.setGeometry(QtCore.QRect(-40, -70, 120, 150))
        frame_16.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px")
        frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_16.setObjectName("frame_16")
        frame_17 = QtWidgets.QFrame(Master)
        frame_17.setGeometry(QtCore.QRect(350, 360, 130, 130))
        frame_17.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px")
        frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_17.setObjectName("frame_17")
        frame_18 = QtWidgets.QFrame(Master)
        frame_18.setGeometry(QtCore.QRect(90, -6, 340, 10))
        frame_18.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px")
        frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_18.setObjectName("frame_18")
        frame_19 = QtWidgets.QFrame(Master)
        frame_19.setGeometry(QtCore.QRect(427, 0, 401, 350))
        frame_19.setStyleSheet("background-color: #4169B6;\n"
"")
        frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_19.setObjectName("frame_19")
        frame_20 = QtWidgets.QFrame(Master)
        frame_20.setGeometry(QtCore.QRect(-10, 437, 340, 30))
        frame_20.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 55px")
        frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_20.setObjectName("frame_20")
        frame_21 = QtWidgets.QFrame(Master)
        frame_21.setGeometry(QtCore.QRect(-397, 90, 401, 350))
        frame_21.setStyleSheet("background-color: #4169B6;\n"
"")
        frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        frame_21.setObjectName("frame_21")