# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'this.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from .backgroundDesign import loginFormBg
from .src import *

class Login(object):
    def __init__(self, MainWindow):
        self.login = QtWidgets.QFrame(MainWindow)
        self.login.setGeometry(QtCore.QRect(160, 140, 431, 441))
        self.login.setStyleSheet("border-radius: 25px;\n"
"")
        self.login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.login.setGraphicsEffect(shadow(89))
        
        self.label = QtWidgets.QLabel(self.login)
        self.label.setGeometry(QtCore.QRect(170, 60, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.login)
        self.lineEdit.setGeometry(QtCore.QRect(140, 150, 154, 32))
        self.lineEdit.setToolTip('Enter user name')
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#EBEBEB}"
        "QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_2.setToolTip('Enter password')
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 220, 154, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{border-radius: 15px;background-color: #FFFFFF;border: 1px solid;border-color:#EBEBEB}"
        "QLineEdit:hover{border-color:#4169B6;}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.login)
        self.pushButton.setToolTip('Login')
        self.pushButton.setGeometry(QtCore.QRect(135, 315, 160, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
        "background-color: #FFFFFF;\n"
        "border-radius: 15px;\n"
        "padding-right: 55px;\n"
        "}"
        "QPushButton:hover{\n"
        "background-color: #E3DFDF;\n"
        "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setGraphicsEffect(shadow(110))
        
        self.pushButton1 = QtWidgets.QPushButton(self.login)
        self.pushButton.setToolTip('Register')
        self.pushButton1.setGeometry(QtCore.QRect(135, 380, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon)
        self.pushButton1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setStyleSheet("QPushButton{\n"
        "background-color: #FFFFFF;\n"
        "border-radius: 15px;\n"
        "padding-right: 40px;\n"
        "}"
        "QPushButton:hover{\n"
        "background-color: #E3DFDF;\n"
        "}")
        self.pushButton1.setObjectName("pushButton")
        self.pushButton1.setToolTip('Register')
        self.pushButton1.setGraphicsEffect(shadow(110))

        self.pushButton2 = QtWidgets.QPushButton(self.login)
        self.pushButton2.setToolTip('Show')
        self.pushButton2.setGeometry(QtCore.QRect(329, 230, 20, 16))
        self.pushButton2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon)
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.setStyleSheet("background-color: #E4E4E4;\n"
"border-radius:15px;")
        self.pushButton2.pressed.connect( lambda:show(self.pushButton2,self.lineEdit_2) )
        self.pushButton2.released.connect( lambda:hide(self.pushButton2,self.lineEdit_2) )
        loginFormBg(self.login)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "             Login"))
        self.pushButton1.setText(_translate("MainWindow", "         Register"))
        self.lineEdit.setGraphicsEffect(shadow(110))
        self.lineEdit_2.setGraphicsEffect(shadow(110))
        self.pushButton.setGraphicsEffect(shadow(110))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setGraphicsEffect(shadow(110))
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2.setGraphicsEffect(shadow(110))
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide()

    def hide(self): self.login.hide()
    def userNameEntry(self): return self.lineEdit
    def passwordEntry(self): return self.lineEdit_2
    def loginButton(self): return self.pushButton
    def registerButton(self): return self.pushButton1
    def showhideButton(self): return self.pushButton2
    def master(self): return self.login