# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'this.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from .src import *


class sideBar(object):
    def __init__(self, MainWindow):
        self.side_bar = QtWidgets.QFrame(MainWindow)
        self.side_bar.setGeometry(QtCore.QRect(-80, 150, 140, 350))
        self.side_bar.setStyleSheet("background-color: #4169B6;\n"
"border-radius: 25px;")
        self.side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setObjectName("side_bar")
        self.side_bar.setGraphicsEffect(shadow(145))
        self.pushButton = QtWidgets.QPushButton(self.side_bar)
        self.pushButton.setGeometry(QtCore.QRect(90, 90, 36, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2 = QtWidgets.QPushButton(self.side_bar)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 190, 36, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Image/documents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3 = QtWidgets.QPushButton(self.side_bar)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 290, 36, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.hide()

    def master(self): return self.side_bar

    def accountButton(self): return self.pushButton

    def viewAccountButton(self):return self.pushButton_2

    def userButton(self):return self.pushButton_3

    def hide(self): self.side_bar.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
